[workspace]
members = [
	"crates/riverdeck-core",
	"crates/riverdeck-egui",
	"crates/riverdeck-pi",
	"crates/riverdeck-audio-router",
	"plugins/io.github.sulrwin.riverdeck.starterpack.sdPlugin",
]
resolver = "3"


